name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build Release
        run: cargo build --release

      - name: Create & Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/corescribe.exe"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
